version: '2'

services:
  app:
    image: 'ruschava/helloapp.jar:latest'
    build:
      context: .
    container_name: helloapp
    restart: always
    ports:
      - 8070:8070
    depends_on:
      - db    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/emp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=emp
    expose:
      - "5432:5432" 
      
